---
title: "Setting Global Options for read.abares"
author: "Adam H. Sparks"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Setting Global Options for read.abares}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.width = 7,
  fig.height = 7,
  fig.align = "center",
  fig.path = "vignettes/"
)
```

{read.abares} provides a number of global options that can be set to control the behavior of the package.
These options can be set using the `options()` function in R, but a helper function, `read.abares_options()` is provided for more direct access and convenience.

## Caching

### Enable Caching

By default {read.abares does not cache data downloads between R sessions.
To enable caching data downloads between R sessions, you can use the `read.abares_options()` function with the `caching` argument set to `TRUE`:

```r
read.abares_options(caching = TRUE)
```

### Change the Default Cache Location

{read.abares} uses R's default cache directory, which is typically set to `tools::R_user_dir(package = "read.abares", which = "cache")`.
To change the default cache location, you can specify the `cache_location` argument in the `read.abares_options()` function:

```r 
read.abares_options(cache_location = "your_desired_file_path")
```

For example, to save the cache in your `Downloads` folder, you might use:

```r 
read.abares_options(cache_location = "~/Downloads")
```

For more information on caching, see the vignette on [Caching in read.abares](caching.html).

## Download Options

### User Agent String

{read.abares} provides a default user agent string of `read.abares` but you can change it for your own use, _e.g._, "the user agent should be different on continuous integration services, and in development (based on, for instance, the GitHub usernames of the developers)."^[1]
You can change the user agent string using the `user_agent` argument in the `read.abares_options()` function:

```r
read.abares_options(user_agent = "your_custom_user_agent")
```

### Timeout 

By default {read.abares} provides a very generous timeout value to keep the connection alive when downloading the large files, `2000`.
However, this can be overridden using the `timeout` argument in the `read.abares_options()` function:

```r
read.abares_options(timeout = 1000) # set timeout to 1000 seconds
```

### Retries

{read.abares} will retry a download if it fails, up to a maximum number of retries.
By default, this is set to `3`.
You may override this using the `retries` argument in the `read.abares_options()` function:

```r
read.abares_options(retries = 5) # set retries to 5
```

[^1]: rOpenSci Developers' Guide: <https://devguide.ropensci.org/pkg_building.html#packages-wrapping-web-resources-api-clients>
