# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "region_code", # <parse_abs_production_data>
  "data_item", # <parse_abs_production_data>
  ".x", # <read_aagis_regions>
  ".x", # <read_abares_trade>
  "Year_month", # <read_abares_trade>
  ".x", # <read_abares_trade_regions>
  ".x", # <read_abs_broadacre_data>
  ".x", # <read_abs_horticulture_data>
  ".x", # <read_abs_livestock_data>
  "lat", # <read_agfd_dt>
  "lon", # <read_agfd_dt>
  ".x", # <read_clum_commodities>
  ".x", # <read_estimates_by_performance_category>
  ".x", # <read_estimates_by_size>
  ".x", # <read_historical_forecast_database>
  "Month_issued", # <read_historical_forecast_database>
  ".x", # <read_historical_national_estimates>
  ".x", # <read_historical_regional_estimates>
  ".x", # <read_historical_state_estimates>
  "clum_metadata_pdf", # <view_clum_metadata_pdf>
  NULL
))
