# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "region_codes", # <parse_abs_production_data>
  "data_item", # <parse_abs_production_data>
  "Year_month", # <.download_abares_trade>
  "lat", # <read_agfd_dt>
  "lon", # <read_agfd_dt>
  "Month_issued", # <read_historical_forecast_database>
  NULL
))
