# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "y", # <get_agfd>
  "Year_month", # <.download_abares_trade>
  "lat", # <read_agfd_dt>
  "lon", # <read_agfd_dt>
  "Month_issued", # <read_historical_forecast_database>
  NULL
))
